/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chat.socket.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ChatConfigure service. Represents a row in the &quot;DLF_ChatConfigure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.chat.socket.model.impl.ChatConfigureModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.chat.socket.model.impl.ChatConfigureImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChatConfigure
 * @generated
 */
@ProviderType
public interface ChatConfigureModel
	extends BaseModel<ChatConfigure>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chat configure model instance should use the {@link ChatConfigure} interface instead.
	 */

	/**
	 * Returns the primary key of this chat configure.
	 *
	 * @return the primary key of this chat configure
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chat configure.
	 *
	 * @param primaryKey the primary key of this chat configure
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this chat configure.
	 *
	 * @return the uuid of this chat configure
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this chat configure.
	 *
	 * @param uuid the uuid of this chat configure
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this chat configure.
	 *
	 * @return the ID of this chat configure
	 */
	public long getId();

	/**
	 * Sets the ID of this chat configure.
	 *
	 * @param id the ID of this chat configure
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this chat configure.
	 *
	 * @return the group ID of this chat configure
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this chat configure.
	 *
	 * @param groupId the group ID of this chat configure
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this chat configure.
	 *
	 * @return the company ID of this chat configure
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this chat configure.
	 *
	 * @param companyId the company ID of this chat configure
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this chat configure.
	 *
	 * @return the user ID of this chat configure
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this chat configure.
	 *
	 * @param userId the user ID of this chat configure
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this chat configure.
	 *
	 * @return the user uuid of this chat configure
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this chat configure.
	 *
	 * @param userUuid the user uuid of this chat configure
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this chat configure.
	 *
	 * @return the user name of this chat configure
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this chat configure.
	 *
	 * @param userName the user name of this chat configure
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this chat configure.
	 *
	 * @return the create date of this chat configure
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this chat configure.
	 *
	 * @param createDate the create date of this chat configure
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this chat configure.
	 *
	 * @return the modified date of this chat configure
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this chat configure.
	 *
	 * @param modifiedDate the modified date of this chat configure
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the enable of this chat configure.
	 *
	 * @return the enable of this chat configure
	 */
	public boolean getEnable();

	/**
	 * Returns <code>true</code> if this chat configure is enable.
	 *
	 * @return <code>true</code> if this chat configure is enable; <code>false</code> otherwise
	 */
	public boolean isEnable();

	/**
	 * Sets whether this chat configure is enable.
	 *
	 * @param enable the enable of this chat configure
	 */
	public void setEnable(boolean enable);

	/**
	 * Returns the header color of this chat configure.
	 *
	 * @return the header color of this chat configure
	 */
	@AutoEscape
	public String getHeaderColor();

	/**
	 * Sets the header color of this chat configure.
	 *
	 * @param headerColor the header color of this chat configure
	 */
	public void setHeaderColor(String headerColor);

	/**
	 * Returns the chat right color of this chat configure.
	 *
	 * @return the chat right color of this chat configure
	 */
	@AutoEscape
	public String getChatRightColor();

	/**
	 * Sets the chat right color of this chat configure.
	 *
	 * @param chatRightColor the chat right color of this chat configure
	 */
	public void setChatRightColor(String chatRightColor);

	/**
	 * Returns the chat left color of this chat configure.
	 *
	 * @return the chat left color of this chat configure
	 */
	@AutoEscape
	public String getChatLeftColor();

	/**
	 * Sets the chat left color of this chat configure.
	 *
	 * @param chatLeftColor the chat left color of this chat configure
	 */
	public void setChatLeftColor(String chatLeftColor);

	/**
	 * Returns the header text color of this chat configure.
	 *
	 * @return the header text color of this chat configure
	 */
	@AutoEscape
	public String getHeaderTextColor();

	/**
	 * Sets the header text color of this chat configure.
	 *
	 * @param headerTextColor the header text color of this chat configure
	 */
	public void setHeaderTextColor(String headerTextColor);

	/**
	 * Returns the content text color of this chat configure.
	 *
	 * @return the content text color of this chat configure
	 */
	@AutoEscape
	public String getContentTextColor();

	/**
	 * Sets the content text color of this chat configure.
	 *
	 * @param contentTextColor the content text color of this chat configure
	 */
	public void setContentTextColor(String contentTextColor);

	/**
	 * Returns the back color of this chat configure.
	 *
	 * @return the back color of this chat configure
	 */
	@AutoEscape
	public String getBackColor();

	/**
	 * Sets the back color of this chat configure.
	 *
	 * @param backColor the back color of this chat configure
	 */
	public void setBackColor(String backColor);

	/**
	 * Returns the chat role ID of this chat configure.
	 *
	 * @return the chat role ID of this chat configure
	 */
	@AutoEscape
	public String getChatRoleId();

	/**
	 * Sets the chat role ID of this chat configure.
	 *
	 * @param chatRoleId the chat role ID of this chat configure
	 */
	public void setChatRoleId(String chatRoleId);

	/**
	 * Returns the font family of this chat configure.
	 *
	 * @return the font family of this chat configure
	 */
	@AutoEscape
	public String getFontFamily();

	/**
	 * Sets the font family of this chat configure.
	 *
	 * @param fontFamily the font family of this chat configure
	 */
	public void setFontFamily(String fontFamily);

	/**
	 * Returns the request feature of this chat configure.
	 *
	 * @return the request feature of this chat configure
	 */
	public boolean getRequestFeature();

	/**
	 * Returns <code>true</code> if this chat configure is request feature.
	 *
	 * @return <code>true</code> if this chat configure is request feature; <code>false</code> otherwise
	 */
	public boolean isRequestFeature();

	/**
	 * Sets whether this chat configure is request feature.
	 *
	 * @param requestFeature the request feature of this chat configure
	 */
	public void setRequestFeature(boolean requestFeature);

	@Override
	public ChatConfigure cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}